version: "3.7"

services:
  # База данных PostgreSQL
  db:
    image: postgres:17.5-alpine
    volumes:
      - ./app_data/data/db/pgdata:/var/lib/postgresql/pgdata
    privileged: true
    restart: always
    ports:
      - '5432:5432'


    environment:
      POSGRES_DB: 'branddb'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123'
      PGDATA: '/var/lib/postgresql/pgdata'

  backend:
      build: ./backend
      command: bash -c "python -m uvicorn mainapp.main:app --reload"
      environment:
          - PATH=/directory/bin:$PATH
      privileged: true
      restart: always
      ports:
          - 8000:8000
      depends_on: 
          - db
