"""Init

Revision ID: be2080e5f95d
Revises: 5bff77acd29d
Create Date: 2025-06-20 01:28:01.928584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be2080e5f95d'
down_revision: Union[str, None] = '5bff77acd29d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'countries', ['id'])
    op.create_unique_constraint(None, 'countries_to_brands_rel', ['id'])
    op.create_unique_constraint(None, 'countries_to_crosses_rel', ['id'])
    op.create_unique_constraint(None, 'crosses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crosses', type_='unique')
    op.drop_constraint(None, 'countries_to_crosses_rel', type_='unique')
    op.drop_constraint(None, 'countries_to_brands_rel', type_='unique')
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    # ### end Alembic commands ###
