"""Initial revision

Revision ID: e1e8265e868b
Revises: 8a27de113174
Create Date: 2025-06-18 02:51:04.226455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e8265e868b'
down_revision: Union[str, None] = '8a27de113174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'brands', ['id'])
    op.create_unique_constraint(None, 'countries', ['id'])
    op.create_unique_constraint(None, 'crosses', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crosses', type_='unique')
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_constraint(None, 'brands', type_='unique')
    # ### end Alembic commands ###
