"""Add many to many for countries

Revision ID: e5634af3aba6
Revises: c58499bc4f5b
Create Date: 2025-06-19 04:33:45.516055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5634af3aba6'
down_revision: Union[str, None] = 'c58499bc4f5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries_to_brands_rel', sa.Column('country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'countries_to_brands_rel', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'countries_to_brands_rel', type_='foreignkey')
    op.drop_column('countries_to_brands_rel', 'country_id')
    # ### end Alembic commands ###
